### ISSUE TITLE
How to swap only two items without affecting positions of other items in Drag Grid Layout ?

### ISSUE THREAD

**Issue by TapanHp** [h6ah4i/android-advancedrecyclerview#269] opened 2016-06-22 06:40 UTC
what if i want to change positions of two items without affecting positions of other elements, like static swap of two items, and all remaining elements in grid will stay at same positions they had.

for example : 
Let us consider grid layout with 3 columns and two rows that means only 6 elements.

 i drag item from position 6 to 0th position and i want that two elements are only changing position but what happening is 6th element is on first position and all other elements are changed now with increased position by one.

Is there any way to handle my case that only two element will change and no others, we are making a puzzle game so please if anyone can help it would b great !!
by the way You guyss made awesome library , i have been used it for many projects. 
thanks in advanced.

**Comment by h6ah4i** [comment] 2016-06-25 15:58
Thank you for the suggestion. I will try to add it. (duplicate of 253)

**Comment by TapanHp** [comment] 2016-06-26 14:08
Please let me know when you get done it.
And thanks for making efforts for solution.

**Closed** 2016-07-03 11:26 UTC
Labels: enhancement
