### ISSUE TITLE
Crash When Dragging and Swiping

### ISSUE THREAD

**Issue by agrosner** [h6ah4i/android-advancedrecyclerview#132] opened 2015-10-20 15:29 UTC
Version: 0.8.1
Support Lib Version: 23.0.1

It's pretty easy to reproduce:
1. Drag an Item
2. Swipe to delete an item
3. Drag said item again.
4. Crash:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v4.view.ViewPropertyAnimatorUpdateListener.onAnimationUpdate(android.view.View)' on a null object reference
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatKK$1.onAnimationUpdate(ViewPropertyAnimatorCompatKK.java:28)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationUpdate(ViewPropertyAnimator.java:1191)
             E/AndroidRuntime:     at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
             E/AndroidRuntime:     at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
             E/AndroidRuntime:     at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
             E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
             E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatICS.start(ViewPropertyAnimatorCompatICS.java:130)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.start(ViewPropertyAnimatorCompat.java:497)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat.start(ViewPropertyAnimatorCompat.java:1235)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.startActiveItemAnimation(BaseItemAnimationManager.java:173)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onCreateAnimation(SwipeDismissItemAnimator.java:330)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onCreateAnimation(SwipeDismissItemAnimator.java:306)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.createAnimation(BaseItemAnimationManager.java:152)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.runPendingAnimations(BaseItemAnimationManager.java:91)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.schedulePendingAnimationsByDefaultRule(GeneralItemAnimator.java:269)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator.onSchedulePendingAnimations(SwipeDismissItemAnimator.java:54)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.runPendingAnimations(GeneralItemAnimator.java:62)
```
Whats happening is that the `animator.setListener(null)` in line 85 of `BaseDraggableItemDecorator` is getting nulled out. This means that it causes a crash in the support library.

**Comment by agrosner** [comment] 2015-10-20 15:36
also fails at support lib v23.1.0 and version 0.8.2

**Comment by agrosner** [comment] 2015-10-20 15:53
or it might be that the `animator` in `onCreateAnimation` does not have a listener.

**Comment by agrosner** [comment] 2015-10-20 16:00
both cases are valid. and another crash:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v4.view.ViewPropertyAnimatorUpdateListener.onAnimationUpdate(android.view.View)' on a null object reference
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatKK$1.onAnimationUpdate(ViewPropertyAnimatorCompatKK.java:28)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationUpdate(ViewPropertyAnimator.java:1191)
             E/AndroidRuntime:     at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
             E/AndroidRuntime:     at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
             E/AndroidRuntime:     at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
             E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
             E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:903)
             E/AndroidRuntime:     at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:415)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatICS.start(ViewPropertyAnimatorCompatICS.java:130)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.start(ViewPropertyAnimatorCompat.java:497)
             E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat.start(ViewPropertyAnimatorCompat.java:1235)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.BaseDraggableItemDecorator.moveToDefaultPosition(BaseDraggableItemDecorator.java:99)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.DraggingItemDecorator.finish(DraggingItemDecorator.java:168)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.finishDragging(RecyclerViewDragDropManager.java:677)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleActionUpOrCancel(RecyclerViewDragDropManager.java:764)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.onTouchEvent(RecyclerViewDragDropManager.java:500)
             E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager$1.onTouchEvent(RecyclerViewDragDropManager.java:173)
             E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2102)
```

**Comment by agrosner** [comment] 2015-10-20 18:59
A hint its nexus 5 running 6.0

**Comment by h6ah4i** [comment] 2015-10-20 22:52
Duplicate of #121.

**Closed** 2016-02-07 07:15 UTC
Labels: question
