### ISSUE TITLE
MyExpandableItemAdapter

### ISSUE THREAD

**Issue by FreakMurderer** [h6ah4i/android-advancedrecyclerview#79] opened 2015-08-08 17:25 UTC
Hello 
When i choose last element in Expandable recyclerView (com.h6ah4i.android.example.advrecyclerview.demo_e.RecyclerListViewFragment)
 last group not expand automatically i need to swype manually.
Look at video:
http://1drv.ms/1IVk5Pl

**Comment by h6ah4i** [comment] 2015-08-11 14:19
duplicate of #60.

**Comment by h6ah4i** [comment] 2015-10-03 11:01
Fixed in 0.8.0.

**Closed by h6ah4i** 2015-10-03 11:01 UTC
