### ISSUE TITLE
How to expand all group by default?

### ISSUE THREAD

**Issue by justplay1** [h6ah4i/android-advancedrecyclerview#100] opened 2015-09-08 19:25 UTC
It is possible to expand group by default?

**Comment by h6ah4i** [comment] 2015-09-09 15:49
Hi. This issue is duplicate of the issue #57. I have added the`RecyclerViewExpandableItemManager.expandAll()` method to solve the issue, but it is available only on the develop branch code for now. It will be included the next v0.8.0 release.

Related:
- Issue #57 How to add groups "expanded" right away?
- PR #97 Feature/add notify expanded group items insertion method #96

**Comment by justplay1** [comment] 2015-09-09 16:21
h6ah4i, Thanks. Wait for 0.8.0

**Comment by h6ah4i** [comment] 2015-10-03 08:02
Hi. I have just published v0.8.0.

**Closed by h6ah4i** 2015-10-03 08:02 UTC
Labels: question
